from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Protocol


class Repository(Protocol):
    backend_name: str

    def transaction(self) -> AbstractContextManager[None]: ...
    def reset(self) -> dict: ...
    def next_number(self, sequence_name: str) -> int: ...

    def list_accounts(self) -> list[dict]: ...
    def get_account(self, account_id: str) -> dict | None: ...
    def insert_account(self, account: dict) -> None: ...
    def update_account(self, account: dict) -> None: ...

    def insert_customer(self, customer: dict) -> None: ...
    def get_customer(self, customer_id: str) -> dict | None: ...
    def update_customer(self, customer: dict) -> None: ...

    def get_contract(self, contract_id: str) -> dict | None: ...
    def insert_contract(self, contract: dict) -> None: ...

    def insert_legacy_account(self, legacy_account: dict) -> None: ...
    def get_legacy_account(self, legacy_account_ref: str) -> dict | None: ...
    def list_legacy_accounts(self) -> list[dict]: ...
    def insert_legacy_line(self, legacy_line: dict) -> None: ...
    def get_legacy_line(self, legacy_line_ref: str) -> dict | None: ...
    def list_legacy_lines(self, legacy_account_ref: str) -> list[dict]: ...

    def find_subscription_by_source(
        self, account_id: str, source_subscription_ref: str
    ) -> dict | None: ...
    def find_subscription_by_sim(self, sim_id: str) -> dict | None: ...
    def insert_subscription(self, subscription: dict) -> None: ...
    def update_subscription(self, subscription: dict) -> None: ...
    def list_subscriptions(self, account_id: str) -> list[dict]: ...

    def list_sims(self, account_id: str | None = None) -> list[dict]: ...
    def list_account_resource_views(self, account_id: str) -> list[dict]: ...
    def get_sim(self, sim_resource_id: str) -> dict | None: ...
    def insert_sim(self, sim: dict) -> None: ...
    def update_sim(self, sim: dict) -> None: ...
    def list_mdns(self, status: str | None = None) -> list[dict]: ...
    def get_mdn(self, mdn_resource_id: str) -> dict | None: ...
    def update_mdn(self, mdn: dict) -> None: ...
    def insert_subscription_resource(self, resource: dict) -> None: ...
    def update_subscription_resource(self, resource: dict) -> None: ...
    def list_subscription_resources(self, subscription_id: str) -> list[dict]: ...

    def insert_activation_batch(self, batch: dict) -> None: ...
    def update_activation_batch(self, batch: dict) -> None: ...
    def get_activation_batch(self, batch_id: str) -> dict | None: ...
    def list_activation_batches(self, account_id: str | None = None) -> list[dict]: ...
    def insert_activation_batch_item(self, item: dict) -> None: ...
    def update_activation_batch_item(self, item: dict) -> None: ...
    def list_activation_batch_items(self, batch_id: str) -> list[dict]: ...
    def insert_flowone_element_result(self, result: dict) -> None: ...
    def list_flowone_element_results(self, batch_item_id: str) -> list[dict]: ...

    def insert_network_activation(self, row: dict) -> None: ...
    def get_network_activation(self, activation_id: str) -> dict | None: ...
    def insert_legacy_subscription_action(self, row: dict) -> None: ...
    def get_legacy_subscription_action(self, compatibility_action_id: str) -> dict | None: ...

    def insert_audit_event(self, event: dict) -> None: ...
    def insert_activation_event(self, event: dict) -> None: ...

    def delete_billing_for_account_cycle(self, account_id: str, bill_cycle: str) -> None: ...
    def insert_charge(self, charge: dict) -> None: ...
    def insert_billing_row(self, row: dict) -> None: ...
    def insert_bill_run(self, run: dict) -> None: ...
    def get_bill_run(self, bill_run_id: str) -> dict | None: ...
    def list_bill_runs(self, account_id: str | None = None) -> list[dict]: ...
    def list_charges(self, bill_run_id: str) -> list[dict]: ...
    def list_billing_rows(self, bill_run_id: str) -> list[dict]: ...
    def latest_bill_run(self, account_id: str, bill_cycle: str) -> dict | None: ...
